In [1]:
import pandas as pd

In [9]:
import os

In [2]:
import sqlalchemy
import psycopg2
print("SQLAlchemy version:", sqlalchemy.__version__)
print("psycopg2 version:", psycopg2.__version__)

SQLAlchemy version: 2.0.41
psycopg2 version: 2.9.10 (dt dec pq3 ext lo64)

In [3]:
from sqlalchemy import create_engine, text
from sqlalchemy.exc import OperationalError

In [ ]:
#Connect to the database running in docker
# need to define host and port when connecting to a docker container
conn = psycopg2.connect(dbname = "eiadb", user = "postgres", password = "mysecretpassword", host = "localhost", port = "5432")

In [ ]:
#get cursor
cur = conn.cursor()

In [ ]:
table_info = "SELECT table_name FROM information_schema.tables WHERE table_schema = 'public'"

In [ ]:
cur.execute(table_info)

In [ ]:
cur.fetchall()

In [ ]:
cur.execute("Select * FROM fact_gen")
cur.fetchall()

In [ ]:
cur.description

In [ ]:
cur.execute("Select * FROM dim_state")
cur.description

In [3]:
# Insert data from a data frame
# Fake data
data = {"state_code": ["KS", "MO"],
        "state_name": ["Kansas", "Missouri"],
        "census_region": ["Midwest", "Midwest"]
       }
df = pd.DataFrame(data)
df.head()

  state_code state_name census_region
0         KS     Kansas       Midwest
1         MO   Missouri       Midwest

In [ ]:
df.to_sql(name = "dim_state", con = conn, if_exists= "append")

### SQLAlchemy
- the engine creates the connection to the database, connection factory
    - do not create per object or per functino call, once is enough
- the connection (created by the enigee) calls SQL statements
    - should be used in a with statement to manage context

In [ ]:
# create engine
# postgresql+psycopg2://user:password@host:port/dbname[?key=value&key=value...]
# dbname = "eiadb", user = "postgres", password = "mysecretpassword", host = "localhost", port = "5432"

In [ ]:
# add data
# engine.begin() creates a connection and a transaction, will auto roll back if error is raised
# df.to_sql(name = "dim_state", con = conn, if_exists= "append")
with engine.begin() as connection:
    df.to_sql(name='dim_state', con=connection, if_exists='append')

In [20]:
drop_state = text(
"DROP TABLE IF EXISTS dim_state CASCADE"
)

In [30]:
load_state = text("CREATE TABLE dim_state(state_id SERIAL PRIMARY KEY,state_short VARCHAR(5) NOT NULL UNIQUE,state_long VARCHAR(50) NOT NULL)")

In [31]:
with engine.begin() as conn:
    result = conn.execute(drop_state)

In [32]:
with engine.begin() as conn:
    result = conn.execute(load_state)
result

In [33]:
with engine.connect() as conn:
    result = conn.execute(text("SELECT * FROM dim_state"))
result.keys()

RMKeyView(['state_id', 'state_short', 'state_long'])

### get_engine

In [6]:
# 1. Create the engine (do this once, reuse it)
engine = create_engine(
    "postgresql+psycopg2://postgres:mysecretpassword@localhost:5432/eiadb"
)

In [7]:
# 2. Test the connection
try:
    with engine.connect() as conn:
        conn.execute(text("SELECT 1"))
    print(f"Connection successful")
except OperationalError as e:
    print(f"Connection failed — could not reach")
    print(f"Details: {e}")

Connection successful

### get states data

In [ ]:
dataIn_path = "../data/raw"
price_df = pd.read_csv(os.path.join(dataIn_path, "price_data.csv"))
state_series = pd.Series(price_df.stateDescription.values, index=price_df.stateid).drop_duplicates()
state_df = state_series.reset_index()
state_df = state_df.rename(columns = {"stateid": "state_short", 0: "state_long"})
state_df

### load states

In [ ]:
# 3. Load a DataFrame into a table
with engine.connect() as conn:
    state_df.to_sql(name='dim_state', con=conn, if_exists='append', index=False)
    conn.commit()
    print("Loaded", len(state_df), "rows into dim_state")

In [ ]:
with engine.connect() as conn:
    result = conn.execute(text("SELECT * FROM dim_state")).fetchall()
result

In [37]:
tableName = "stateTable"
print("Loaded", len(state_df), f"rows into {tableName}")

Loaded 62 rows into stateTable

### get_states_map

In [ ]:
with engine.connect() as conn:
    result = conn.execute(text("SELECT state_short, state_id FROM dim_state")).fetchall()
#result
state_map = dict(result)
state_map

In [38]:
with engine.connect() as conn:
    result = conn.execute(text("SELECT * FROM dim_state"))
result.keys()

RMKeyView(['state_id', 'state_short', 'state_long'])

In [16]:
delete_dim = text("DELETE FROM dim_state")

In [17]:
with engine.begin() as connection:
    connection.execute(delete_dim)
    result = connection.execute(text("SELECT * FROM dim_state")).fetchall()
result

[]

### get dates
date_id, year, month, month_name, quarter

In [44]:
dataIn_path = "../data/raw"
price_df = pd.read_csv(os.path.join(dataIn_path, "price_data.csv"))
#date_series = pd.Series(price_df.stateDescription.values, index=price_df.stateid).drop_duplicates()
#state_df = state_series.reset_index()
price_df.head()

,period,stateid,stateDescription,sectorid,sectorName,price,price-units
0,2025-03,AK,Alaska,ALL,all sectors,22.96,cents per kilowatt-hour
1,2025-03,AK,Alaska,COM,commercial,22.10,cents per kilowatt-hour
2,2025-03,AK,Alaska,IND,industrial,20.17,cents per kilowatt-hour
3,2025-03,AK,Alaska,OTH,other,NaN,cents per kilowatt-hour
4,2025-03,AK,Alaska,RES,residential,25.79,cents per kilowatt-hour

In [46]:
price_df.dtypes

period                  str
stateid                 str
stateDescription        str
sectorid                str
sectorName              str
price               float64
price-units             str
dtype: object