In [13]:
import requests
import pandas as pd

In [2]:
#need to hide this but im too lazy rn
EIA_KEY = "W3ts2Rhqau0j0khKCCqMtdmOf01HBNLgl2Y8mVNF"

In [5]:
base_url = "https://api.eia.gov/v2/electricity/rto/daily-fuel-type-data/data"

In [13]:
params = {
    "length": 100,
    "api_key": EIA_KEY
}

In [14]:
response = requests.get(base_url, params)

In [11]:
response.raise_for_status()

In [15]:
# .json() returns the response as a dictonary
response.json()

{'warnings': [{'warning': 'incomplete return',
   'description': 'The API can only return 5000 rows in JSON format.  Please consider constraining your request with facet, start, or end, or using offset to paginate results.'}],
 'response': {'total': '5258005',
  'dateFormat': 'YYYY-MM-DD',
  'frequency': 'daily',
  'data': [{'period': '2026-03-31',
    'respondent': 'AECI',
    'respondent-name': 'Associated Electric Cooperative, Inc.',
    'fueltype': 'COL',
    'type-name': 'Coal',
    'timezone': 'Arizona',
    'timezone-description': 'Arizona'},
   {'period': '2026-03-31',
    'respondent': 'AECI',
    'respondent-name': 'Associated Electric Cooperative, Inc.',
    'fueltype': 'COL',
    'type-name': 'Coal',
    'timezone': 'Central',
    'timezone-description': 'Central'},
   {'period': '2026-03-31',
    'respondent': 'AECI',
    'respondent-name': 'Associated Electric Cooperative, Inc.',
    'fueltype': 'COL',
    'type-name': 'Coal',
    'timezone': 'Eastern',
    'timezone-description': 'Eastern'},
   {'period': '2026-03-31',
    'respondent': 'AECI',
    'respondent-name': 'Associated Electric Cooperative, Inc.',
    'fueltype': 'COL',
    'type-name': 'Coal',
    'timezone': 'Mountain',
    'timezone-description': 'Mountain'},
   {'period': '2026-03-31',
    'respondent': 'AECI',
    'respondent-name': 'Associated Electric Cooperative, Inc.',
    'fueltype': 'COL',
    'type-name': 'Coal',
    'timezone': 'Pacific',
    'timezone-description': 'Pacific'},
   {'period': '2026-03-31',
    'respondent': 'AECI',
    'respondent-name': 'Associated Electric Cooperative, Inc.',
    'fueltype': 'NG',
    'type-name': 'Natural Gas',
    'timezone': 'Arizona',
    'timezone-description': 'Arizona'},
   {'period': '2026-03-31',
    'respondent': 'AECI',
    'respondent-name': 'Associated Electric Cooperative, Inc.',
    'fueltype': 'NG',
    'type-name': 'Natural Gas',
    'timezone': 'Central',
    'timezone-description': 'Central'},
   {'period': '2026-03-31',
    'respondent': 'AECI',
    'respondent-name': 'Associated Electric Cooperative, Inc.',
    'fueltype': 'NG',
    'type-name': 'Natural Gas',
    'timezone': 'Eastern',
    'timezone-description': 'Eastern'},
   {'period': '2026-03-31',
    'respondent': 'AECI',
    'respondent-name': 'Associated Electric Cooperative, Inc.',
    'fueltype': 'NG',
    'type-name': 'Natural Gas',
    'timezone': 'Mountain',
    'timezone-description': 'Mountain'},
   {'period': '2026-03-31',
    'respondent': 'AECI',
    'respondent-name': 'Associated Electric Cooperative, Inc.',
    'fueltype': 'NG',
    'type-name': 'Natural Gas',
    'timezone': 'Pacific',
    'timezone-description': 'Pacific'},
   {'period': '2026-03-31',
    'respondent': 'AECI',
    'respondent-name': 'Associated Electric Cooperative, Inc.',
    'fueltype': 'WND',
    'type-name': 'Wind',
    'timezone': 'Arizona',
    'timezone-description': 'Arizona'},
   {'period': '2026-03-31',
    'respondent': 'AECI',
    'respondent-name': 'Associated Electric Cooperative, Inc.',
    'fueltype': 'WND',
    'type-name': 'Wind',
    'timezone': 'Central',
    'timezone-description': 'Central'},
   {'period': '2026-03-31',
    'respondent': 'AECI',
    'respondent-name': 'Associated Electric Cooperative, Inc.',
    'fueltype': 'WND',
    'type-name': 'Wind',
    'timezone': 'Eastern',
    'timezone-description': 'Eastern'},
   {'period': '2026-03-31',
    'respondent': 'AECI',
    'respondent-name': 'Associated Electric Cooperative, Inc.',
    'fueltype': 'WND',
    'type-name': 'Wind',
    'timezone': 'Mountain',
    'timezone-description': 'Mountain'},
   {'period': '2026-03-31',
    'respondent': 'AECI',
    'respondent-name': 'Associated Electric Cooperative, Inc.',
    'fueltype': 'WND',
    'type-name': 'Wind',
    'timezone': 'Pacific',
    'timezone-description': 'Pacific'},
   {'period': '2026-03-31',
    'respondent': 'AVA',
    'respondent-name': 'Avista Corporation',
    'fueltype': 'NG',
    'type-name': 'Natural Gas',
    'timezone': 'Arizona',
    'timezone-description': 'Arizona'},
   {'period': '2026-03-31',
    'respondent': 'AVA',
    'respondent-name': 'Avista Corporation',
    'fueltype': 'NG',
    'type-name': 'Natural Gas',
    'timezone': 'Central',
    'timezone-description': 'Central'},
   {'period': '2026-03-31',
    'respondent': 'AVA',
    'respondent-name': 'Avista Corporation',
    'fueltype': 'NG',
    'type-name': 'Natural Gas',
    'timezone': 'Eastern',
    'timezone-description': 'Eastern'},
   {'period': '2026-03-31',
    'respondent': 'AVA',
    'respondent-name': 'Avista Corporation',
    'fueltype': 'NG',
    'type-name': 'Natural Gas',
    'timezone': 'Mountain',
    'timezone-description': 'Mountain'},
   {'period': '2026-03-31',
    'respondent': 'AVA',
    'respondent-name': 'Avista Corporation',
    'fueltype': 'NG',
    'type-name': 'Natural Gas',
    'timezone': 'Pacific',
    'timezone-description': 'Pacific'},
   {'period': '2026-03-31',
    'respondent': 'AVA',
    'respondent-name': 'Avista Corporation',
    'fueltype': 'OTH',
    'type-name': 'Other',
    'timezone': 'Arizona',
    'timezone-description': 'Arizona'},
   {'period': '2026-03-31',
    'respondent': 'AVA',
    'respondent-name': 'Avista Corporation',
    'fueltype': 'OTH',
    'type-name': 'Other',
    'timezone': 'Central',
    'timezone-description': 'Central'},
   {'period': '2026-03-31',
    'respondent': 'AVA',
    'respondent-name': 'Avista Corporation',
    'fueltype': 'OTH',
    'type-name': 'Other',
    'timezone': 'Eastern',
    'timezone-description': 'Eastern'},
   {'period': '2026-03-31',
    'respondent': 'AVA',
    'respondent-name': 'Avista Corporation',
    'fueltype': 'OTH',
    'type-name': 'Other',
    'timezone': 'Mountain',
    'timezone-description': 'Mountain'},
   {'period': '2026-03-31',
    'respondent': 'AVA',
    'respondent-name': 'Avista Corporation',
    'fueltype': 'OTH',
    'type-name': 'Other',
    'timezone': 'Pacific',
    'timezone-description': 'Pacific'},
   {'period': '2026-03-31',
    'respondent': 'AVA',
    'respondent-name': 'Avista Corporation',
    'fueltype': 'SUN',
    'type-name': 'Solar',
    'timezone': 'Arizona',
    'timezone-description': 'Arizona'},
   {'period': '2026-03-31',
    'respondent': 'AVA',
    'respondent-name': 'Avista Corporation',
    'fueltype': 'SUN',
    'type-name': 'Solar',
    'timezone': 'Central',
    'timezone-description': 'Central'},
   {'period': '2026-03-31',
    'respondent': 'AVA',
    'respondent-name': 'Avista Corporation',
    'fueltype': 'SUN',
    'type-name': 'Solar',
    'timezone': 'Eastern',
    'timezone-description': 'Eastern'},
   {'period': '2026-03-31',
    'respondent': 'AVA',
    'respondent-name': 'Avista Corporation',
    'fueltype': 'SUN',
    'type-name': 'Solar',
    'timezone': 'Mountain',
    'timezone-description': 'Mountain'},
   {'period': '2026-03-31',
    'respondent': 'AVA',
    'respondent-name': 'Avista Corporation',
    'fueltype': 'SUN',
    'type-name': 'Solar',
    'timezone': 'Pacific',
    'timezone-description': 'Pacific'},
   {'period': '2026-03-31',
    'respondent': 'AVA',
    'respondent-name': 'Avista Corporation',
    'fueltype': 'WAT',
    'type-name': 'Hydro',
    'timezone': 'Arizona',
    'timezone-description': 'Arizona'},
   {'period': '2026-03-31',
    'respondent': 'AVA',
    'respondent-name': 'Avista Corporation',
    'fueltype': 'WAT',
    'type-name': 'Hydro',
    'timezone': 'Central',
    'timezone-description': 'Central'},
   {'period': '2026-03-31',
    'respondent': 'AVA',
    'respondent-name': 'Avista Corporation',
    'fueltype': 'WAT',
    'type-name': 'Hydro',
    'timezone': 'Eastern',
    'timezone-description': 'Eastern'},
   {'period': '2026-03-31',
    'respondent': 'AVA',
    'respondent-name': 'Avista Corporation',
    'fueltype': 'WAT',
    'type-name': 'Hydro',
    'timezone': 'Mountain',
    'timezone-description': 'Mountain'},
   {'period': '2026-03-31',
    'respondent': 'AVA',
    'respondent-name': 'Avista Corporation',
    'fueltype': 'WAT',
    'type-name': 'Hydro',
    'timezone': 'Pacific',
    'timezone-description': 'Pacific'},
   {'period': '2026-03-31',
    'respondent': 'AVA',
    'respondent-name': 'Avista Corporation',
    'fueltype': 'WND',
    'type-name': 'Wind',
    'timezone': 'Arizona',
    'timezone-description': 'Arizona'},
   {'period': '2026-03-31',
    'respondent': 'AVA',
    'respondent-name': 'Avista Corporation',
    'fueltype': 'WND',
    'type-name': 'Wind',
    'timezone': 'Central',
    'timezone-description': 'Central'},
   {'period': '2026-03-31',
    'respondent': 'AVA',
    'respondent-name': 'Avista Corporation',
    'fueltype': 'WND',
    'type-name': 'Wind',
    'timezone': 'Eastern',
    'timezone-description': 'Eastern'},
   {'period': '2026-03-31',
    'respondent': 'AVA',
    'respondent-name': 'Avista Corporation',
    'fueltype': 'WND',
    'type-name': 'Wind',
    'timezone': 'Mountain',
    'timezone-description': 'Mountain'},
   {'period': '2026-03-31',
    'respondent': 'AVA',
    'respondent-name': 'Avista Corporation',
    'fueltype': 'WND',
    'type-name': 'Wind',
    'timezone': 'Pacific',
    'timezone-description': 'Pacific'},
   {'period': '2026-03-31',
    'respondent': 'AVRN',
    'respondent-name': 'Avangrid Renewables, LLC',
    'fueltype': 'NG',
    'type-name': 'Natural Gas',
    'timezone': 'Arizona',
    'timezone-description': 'Arizona'},
   {'period': '2026-03-31',
    'respondent': 'AVRN',
    'respondent-name': 'Avangrid Renewables, LLC',
    'fueltype': 'NG',
    'type-name': 'Natural Gas',
    'timezone': 'Central',
    'timezone-description': 'Central'},
   {'period': '2026-03-31',
    'respondent': 'AVRN',
    'respondent-name': 'Avangrid Renewables, LLC',
    'fueltype': 'NG',
    'type-name': 'Natural Gas',
    'timezone': 'Eastern',
    'timezone-description': 'Eastern'},
   {'period': '2026-03-31',
    'respondent': 'AVRN',
    'respondent-name': 'Avangrid Renewables, LLC',
    'fueltype': 'NG',
    'type-name': 'Natural Gas',
    'timezone': 'Mountain',
    'timezone-description': 'Mountain'},
   {'period': '2026-03-31',
    'respondent': 'AVRN',
    'respondent-name': 'Avangrid Renewables, LLC',
    'fueltype': 'NG',
    'type-name': 'Natural Gas',
    'timezone': 'Pacific',
    'timezone-description': 'Pacific'},
   {'period': '2026-03-31',
    'respondent': 'AVRN',
    'respondent-name': 'Avangrid Renewables, LLC',
    'fueltype': 'SUN',
    'type-name': 'Solar',
    'timezone': 'Arizona',
    'timezone-description': 'Arizona'},
   {'period': '2026-03-31',
    'respondent': 'AVRN',
    'respondent-name': 'Avangrid Renewables, LLC',
    'fueltype': 'SUN',
    'type-name': 'Solar',
    'timezone': 'Central',
    'timezone-description': 'Central'},
   {'period': '2026-03-31',
    'respondent': 'AVRN',
    'respondent-name': 'Avangrid Renewables, LLC',
    'fueltype': 'SUN',
    'type-name': 'Solar',
    'timezone': 'Eastern',
    'timezone-description': 'Eastern'},
   {'period': '2026-03-31',
    'respondent': 'AVRN',
    'respondent-name': 'Avangrid Renewables, LLC',
    'fueltype': 'SUN',
    'type-name': 'Solar',
    'timezone': 'Mountain',
    'timezone-description': 'Mountain'},
   {'period': '2026-03-31',
    'respondent': 'AVRN',
    'respondent-name': 'Avangrid Renewables, LLC',
    'fueltype': 'SUN',
    'type-name': 'Solar',
    'timezone': 'Pacific',
    'timezone-description': 'Pacific'},
   {'period': '2026-03-31',
    'respondent': 'AVRN',
    'respondent-name': 'Avangrid Renewables, LLC',
    'fueltype': 'WAT',
    'type-name': 'Hydro',
    'timezone': 'Arizona',
    'timezone-description': 'Arizona'},
   {'period': '2026-03-31',
    'respondent': 'AVRN',
    'respondent-name': 'Avangrid Renewables, LLC',
    'fueltype': 'WAT',
    'type-name': 'Hydro',
    'timezone': 'Central',
    'timezone-description': 'Central'},
   {'period': '2026-03-31',
    'respondent': 'AVRN',
    'respondent-name': 'Avangrid Renewables, LLC',
    'fueltype': 'WAT',
    'type-name': 'Hydro',
    'timezone': 'Eastern',
    'timezone-description': 'Eastern'},
   {'period': '2026-03-31',
    'respondent': 'AVRN',
    'respondent-name': 'Avangrid Renewables, LLC',
    'fueltype': 'WAT',
    'type-name': 'Hydro',
    'timezone': 'Mountain',
    'timezone-description': 'Mountain'},
   {'period': '2026-03-31',
    'respondent': 'AVRN',
    'respondent-name': 'Avangrid Renewables, LLC',
    'fueltype': 'WAT',
    'type-name': 'Hydro',
    'timezone': 'Pacific',
    'timezone-description': 'Pacific'},
   {'period': '2026-03-31',
    'respondent': 'AVRN',
    'respondent-name': 'Avangrid Renewables, LLC',
    'fueltype': 'WND',
    'type-name': 'Wind',
    'timezone': 'Arizona',
    'timezone-description': 'Arizona'},
   {'period': '2026-03-31',
    'respondent': 'AVRN',
    'respondent-name': 'Avangrid Renewables, LLC',
    'fueltype': 'WND',
    'type-name': 'Wind',
    'timezone': 'Central',
    'timezone-description': 'Central'},
   {'period': '2026-03-31',
    'respondent': 'AVRN',
    'respondent-name': 'Avangrid Renewables, LLC',
    'fueltype': 'WND',
    'type-name': 'Wind',
    'timezone': 'Eastern',
    'timezone-description': 'Eastern'},
   {'period': '2026-03-31',
    'respondent': 'AVRN',
    'respondent-name': 'Avangrid Renewables, LLC',
    'fueltype': 'WND',
    'type-name': 'Wind',
    'timezone': 'Mountain',
    'timezone-description': 'Mountain'},
   {'period': '2026-03-31',
    'respondent': 'AVRN',
    'respondent-name': 'Avangrid Renewables, LLC',
    'fueltype': 'WND',
    'type-name': 'Wind',
    'timezone': 'Pacific',
    'timezone-description': 'Pacific'},
   {'period': '2026-03-31',
    'respondent': 'AZPS',
    'respondent-name': 'Arizona Public Service Company',
    'fueltype': 'BAT',
    'type-name': 'Battery storage',
    'timezone': 'Arizona',
    'timezone-description': 'Arizona'},
   {'period': '2026-03-31',
    'respondent': 'AZPS',
    'respondent-name': 'Arizona Public Service Company',
    'fueltype': 'BAT',
    'type-name': 'Battery storage',
    'timezone': 'Central',
    'timezone-description': 'Central'},
   {'period': '2026-03-31',
    'respondent': 'AZPS',
    'respondent-name': 'Arizona Public Service Company',
    'fueltype': 'BAT',
    'type-name': 'Battery storage',
    'timezone': 'Eastern',
    'timezone-description': 'Eastern'},
   {'period': '2026-03-31',
    'respondent': 'AZPS',
    'respondent-name': 'Arizona Public Service Company',
    'fueltype': 'BAT',
    'type-name': 'Battery storage',
    'timezone': 'Mountain',
    'timezone-description': 'Mountain'},
   {'period': '2026-03-31',
    'respondent': 'AZPS',
    'respondent-name': 'Arizona Public Service Company',
    'fueltype': 'BAT',
    'type-name': 'Battery storage',
    'timezone': 'Pacific',
    'timezone-description': 'Pacific'},
   {'period': '2026-03-31',
    'respondent': 'AZPS',
    'respondent-name': 'Arizona Public Service Company',
    'fueltype': 'COL',
    'type-name': 'Coal',
    'timezone': 'Arizona',
    'timezone-description': 'Arizona'},
   {'period': '2026-03-31',
    'respondent': 'AZPS',
    'respondent-name': 'Arizona Public Service Company',
    'fueltype': 'COL',
    'type-name': 'Coal',
    'timezone': 'Central',
    'timezone-description': 'Central'},
   {'period': '2026-03-31',
    'respondent': 'AZPS',
    'respondent-name': 'Arizona Public Service Company',
    'fueltype': 'COL',
    'type-name': 'Coal',
    'timezone': 'Eastern',
    'timezone-description': 'Eastern'},
   {'period': '2026-03-31',
    'respondent': 'AZPS',
    'respondent-name': 'Arizona Public Service Company',
    'fueltype': 'COL',
    'type-name': 'Coal',
    'timezone': 'Mountain',
    'timezone-description': 'Mountain'},
   {'period': '2026-03-31',
    'respondent': 'AZPS',
    'respondent-name': 'Arizona Public Service Company',
    'fueltype': 'COL',
    'type-name': 'Coal',
    'timezone': 'Pacific',
    'timezone-description': 'Pacific'},
   {'period': '2026-03-31',
    'respondent': 'AZPS',
    'respondent-name': 'Arizona Public Service Company',
    'fueltype': 'NG',
    'type-name': 'Natural Gas',
    'timezone': 'Arizona',
    'timezone-description': 'Arizona'},
   {'period': '2026-03-31',
    'respondent': 'AZPS',
    'respondent-name': 'Arizona Public Service Company',
    'fueltype': 'NG',
    'type-name': 'Natural Gas',
    'timezone': 'Central',
    'timezone-description': 'Central'},
   {'period': '2026-03-31',
    'respondent': 'AZPS',
    'respondent-name': 'Arizona Public Service Company',
    'fueltype': 'NG',
    'type-name': 'Natural Gas',
    'timezone': 'Eastern',
    'timezone-description': 'Eastern'},
   {'period': '2026-03-31',
    'respondent': 'AZPS',
    'respondent-name': 'Arizona Public Service Company',
    'fueltype': 'NG',
    'type-name': 'Natural Gas',
    'timezone': 'Mountain',
    'timezone-description': 'Mountain'},
   {'period': '2026-03-31',
    'respondent': 'AZPS',
    'respondent-name': 'Arizona Public Service Company',
    'fueltype': 'NG',
    'type-name': 'Natural Gas',
    'timezone': 'Pacific',
    'timezone-description': 'Pacific'},
   {'period': '2026-03-31',
    'respondent': 'AZPS',
    'respondent-name': 'Arizona Public Service Company',
    'fueltype': 'NUC',
    'type-name': 'Nuclear',
    'timezone': 'Arizona',
    'timezone-description': 'Arizona'},
   {'period': '2026-03-31',
    'respondent': 'AZPS',
    'respondent-name': 'Arizona Public Service Company',
    'fueltype': 'NUC',
    'type-name': 'Nuclear',
    'timezone': 'Central',
    'timezone-description': 'Central'},
   {'period': '2026-03-31',
    'respondent': 'AZPS',
    'respondent-name': 'Arizona Public Service Company',
    'fueltype': 'NUC',
    'type-name': 'Nuclear',
    'timezone': 'Eastern',
    'timezone-description': 'Eastern'},
   {'period': '2026-03-31',
    'respondent': 'AZPS',
    'respondent-name': 'Arizona Public Service Company',
    'fueltype': 'NUC',
    'type-name': 'Nuclear',
    'timezone': 'Mountain',
    'timezone-description': 'Mountain'},
   {'period': '2026-03-31',
    'respondent': 'AZPS',
    'respondent-name': 'Arizona Public Service Company',
    'fueltype': 'NUC',
    'type-name': 'Nuclear',
    'timezone': 'Pacific',
    'timezone-description': 'Pacific'},
   {'period': '2026-03-31',
    'respondent': 'AZPS',
    'respondent-name': 'Arizona Public Service Company',
    'fueltype': 'OIL',
    'type-name': 'Petroleum',
    'timezone': 'Arizona',
    'timezone-description': 'Arizona'},
   {'period': '2026-03-31',
    'respondent': 'AZPS',
    'respondent-name': 'Arizona Public Service Company',
    'fueltype': 'OIL',
    'type-name': 'Petroleum',
    'timezone': 'Central',
    'timezone-description': 'Central'},
   {'period': '2026-03-31',
    'respondent': 'AZPS',
    'respondent-name': 'Arizona Public Service Company',
    'fueltype': 'OIL',
    'type-name': 'Petroleum',
    'timezone': 'Eastern',
    'timezone-description': 'Eastern'},
   {'period': '2026-03-31',
    'respondent': 'AZPS',
    'respondent-name': 'Arizona Public Service Company',
    'fueltype': 'OIL',
    'type-name': 'Petroleum',
    'timezone': 'Mountain',
    'timezone-description': 'Mountain'},
   {'period': '2026-03-31',
    'respondent': 'AZPS',
    'respondent-name': 'Arizona Public Service Company',
    'fueltype': 'OIL',
    'type-name': 'Petroleum',
    'timezone': 'Pacific',
    'timezone-description': 'Pacific'},
   {'period': '2026-03-31',
    'respondent': 'AZPS',
    'respondent-name': 'Arizona Public Service Company',
    'fueltype': 'OTH',
    'type-name': 'Other',
    'timezone': 'Arizona',
    'timezone-description': 'Arizona'},
   {'period': '2026-03-31',
    'respondent': 'AZPS',
    'respondent-name': 'Arizona Public Service Company',
    'fueltype': 'OTH',
    'type-name': 'Other',
    'timezone': 'Central',
    'timezone-description': 'Central'},
   {'period': '2026-03-31',
    'respondent': 'AZPS',

In [ ]:
# why doesn't the length parameter seem to do anything?

In [5]:
# Generation Pull 
# Want to pull, Date, State, Fuel, Generation

gen_url = "https://api.eia.gov/v2/electricity/electric-power-operational-data/data"

gen_params = {
    "frequency": "monthly",
    "data[0]": "generation",
    "start": "2025-01",
    "end": "2025-01",
    "sort[0][column]": "period",
    "sort[0][direction]": "desc",
    "offset": 0,
    "length": 5000,
    "api_key": EIA_KEY
}

In [10]:
#pull the data from the api
gen_res = requests.get(gen_url, gen_params)

In [11]:
#check the request status
gen_res.raise_for_status()

In [ ]:
gen_res.json()

In [14]:
#pull the raw data into a data frame
gen_data = gen_res.json()
gen_df = pd.DataFrame(gen_data['response']['data'])
gen_df.head()

,period,location,stateDescription,sectorid,sectorDescription,fueltypeid,fuelTypeDescription,generation,generation-units
0,2025-01,90,Pacific,1,Electric Utility,ALL,all fuels,19347.63428,thousand megawatthours
1,2025-01,90,Pacific,1,Electric Utility,AOR,all renewables,591.48466,thousand megawatthours
2,2025-01,90,Pacific,1,Electric Utility,BIO,biomass,39.17921,thousand megawatthours
3,2025-01,90,Pacific,1,Electric Utility,COL,"coal, excluding waste coal",47.17936,thousand megawatthours
4,2025-01,90,Pacific,1,Electric Utility,COW,all coal products,47.17936,thousand megawatthours

In [15]:
# Electricty Prices Pull

price_url = "https://api.eia.gov/v2/electricity/retail-sales/data/"

price_params = {
    "frequency": "monthly",
    "data[0]": "price",
    "start": "2025-01",
    "end": "2025-01",
    "sort[0][column]": "period",
    "sort[0][direction]": "desc",
    "offset": 0,
    "length": 5000,
    "api_key": EIA_KEY
}

In [16]:
#pull the data from the api
price_res = requests.get(price_url, price_params)
#check the request status
price_res.raise_for_status()

#Load data into data frame
price_data = price_res.json()
price_df = pd.DataFrame(price_data['response']['data'])
price_df.head()

,period,stateid,stateDescription,sectorid,sectorName,price,price-units
0,2025-01,AK,Alaska,ALL,all sectors,22.63,cents per kilowatt-hour
1,2025-01,AK,Alaska,COM,commercial,21.72,cents per kilowatt-hour
2,2025-01,AK,Alaska,IND,industrial,20.66,cents per kilowatt-hour
3,2025-01,AK,Alaska,OTH,other,NaN,cents per kilowatt-hour
4,2025-01,AK,Alaska,RES,residential,24.73,cents per kilowatt-hour

In [17]:
# Fuel Prices Pull

fuel_url = "https://api.eia.gov/v2/natural-gas/pri/sum/data/"

fuel_params = {
    "frequency": "monthly",
    "data[0]": "value",
    "facets[process][]": "PEU",
    "start": "2025-01",
    "end": "2025-01",
    "sort[0][column]": "period",
    "sort[0][direction]": "desc",
    "offset": 0,
    "length": 5000,
    "api_key": EIA_KEY
}

In [18]:
#pull the data from the api
fuel_res = requests.get(fuel_url, fuel_params)
#check the request status
fuel_res.raise_for_status()

#Load data into data frame
fuel_data = fuel_res.json()
fuel_df = pd.DataFrame(fuel_data['response']['data'])
fuel_df.head()

,period,duoarea,area-name,product,product-name,process,process-name,series,series-description,value,units
0,2025-01,SAR,USA-AR,EPG0,Natural Gas,PEU,Electric Power Price,N3045AR3,Arkansas Natural Gas Price Sold to Electric Po...,NaN,$/MCF
1,2025-01,SSD,USA-SD,EPG0,Natural Gas,PEU,Electric Power Price,N3045SD3,South Dakota Natural Gas Price Sold to Electri...,4.87,$/MCF
2,2025-01,SMO,USA-MO,EPG0,Natural Gas,PEU,Electric Power Price,N3045MO3,Missouri Natural Gas Price Sold to Electric Po...,NaN,$/MCF
3,2025-01,SVA,USA-VA,EPG0,Natural Gas,PEU,Electric Power Price,N3045VA3,Virginia Natural Gas Price Sold to Electric Po...,6.9,$/MCF
4,2025-01,SKS,USA-KS,EPG0,Natural Gas,PEU,Electric Power Price,N3045KS3,Kansas Natural Gas Price Sold to Electric Powe...,7.71,$/MCF

In [ ]:
# TODO How to handle the 5000 row limit for dates?
# I think it is only a problem for the generation data pull